config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  get 'users/index'
  get 'users/show'

   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   match '/signup', to: 'users#new', via: 'get'   
   match '/signin', to: 'sessions#new', via: 'get'
   match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.nombre = nombre.downcase }
	before_create :create_remember_token

	validates :nombre, presence: true, length: {maximum: 5}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, length: {minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(nombre: params[:session][:nombre].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
			#sign the user in and redirect to the user's show page.
		else
			#Create an error message an re-render the signi form.
			flash.now[:error] = 'Invalid user/password combination'
			
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
  	@usuarios = User.all
  end

  def show  	
  	render action: "detalle"
  end

  def detalle
  	@usuario = User.find(paramas[:id])
  end

  def destroy
  	@usuario.destroy
  	redirect_to users_url
  end
  
  def edit
  	
  end

  def update  	
  	if @usuario.update_attributes(user_params)
  		redirect_to users_url
  	else
  		render action: 'edit'
  	end
  end

  def new
  	@usuario = User.new
  end

  def create
  	@usuario = User.new(user_params)
  	if @usuario.save
      sign_in @usuario
  		flash[:success] = "Bienvenido"
      redirect_to @usuario
  		#redirect_to users_url
  	else
  		render 'new'
  	end  	
  end

  private

  def set_user
  	@usuario = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:nombre, :email, :password, :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Planeación Financiera</a>    
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de",   about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Planning App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Inicio", root_path %></li>
          <li><%= link_to "Ayuda", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configuración", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Salir", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Entrar", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiblogApp</title>    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @usuario.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(@usuario.errors.count, "error") %>
  </div>
    <ul>
      <% @usuario.errors.full_messages.each do | msg | %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
</div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("logoSSD106x30.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for(@usuario) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :nombre %> <br>
		<%= f.text_field :nombre %>
	</div>

	<div class="field">
		<%= f.label :email %> <br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %> <br>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %> <br>
		<%= f.password_field :password_confirmation %>
	</div>
	<!-- post -->
	<div class="actions">
		<%= f.submit 'Guardar cambios' %> 
	</div>
<% end %>

app/views/users/detalle.html.erb
<%= @usuario.nombre %>
<%= @usuario.email %>

app/views/users/edit.html.erb
<h1> Editando usuario </h1>
<%= render 'form' %>

<%= link_to 'Atrás', users_path %>

app/views/users/index.html.erb
<h1> Listando usuarios</h1>
	<% flash.each do |key,value| %>
		<div><%= value %></div>
	<% end %>

<table>

<tr>
	<td>Nombre</td>
	<td>Email</td>
</tr>

<% @usuarios.each do |usuario| %>
	<tr>
	<!--metodos generadores de url, Nombrel del router: usuario -> url:/users/1  -->
		<td> <%= link_to usuario.nombre, usuario %></td>
		<td> <%= usuario.email %></td>
		<!--metodos generadores de url, Nombrel del router: edit_user_path(usuario) -> url:/users/1/edit  -->
		<td> <%= link_to "Editar", edit_user_path(usuario) %> </td>
		<td> <%= link_to "Eliminar", usuario, method: :delete, confirm: "Estas seguro?"  %> </td>

	</tr>
<% end %>

<% if @usuarios.size == 0  %>
	USUARIOS NO ENCONTRADOS
<% end%>

</table>
<!-- users/new -->
<%= link_to "Nuevo usuario", new_user_path %>
<%= link_to 'Registrar', '/signup' %>

app/views/users/new.html.erb
<!--<div class="center hero-unit">-->
<h1> Registrar </h1>

<%= render 'form' %>
<!--</div>-->

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>


<%= @usuario.nombre %>
<%= @usuario.email %>